-- Melhorias no Schema: Hábitos e Projetos

-- Hábitos (salvos na tabela tasks)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS icone TEXT DEFAULT '✅';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS streak_updated_at DATE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS meta_semanal INTEGER DEFAULT 7;

-- Projetos
ALTER TABLE projects ADD COLUMN IF NOT EXISTS cor TEXT DEFAULT '#06B6D4';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS icone TEXT DEFAULT '📁';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS notas TEXT DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS arquivado BOOLEAN DEFAULT false;
